### ISSUE TITLE
Issue with flashing cc2650stk

### ISSUE THREAD

**Issue by Anvesh-Chennupati** [lemariva/SensorTag-CC2650#1]
Hey, I am planning to work with cc2650stk. An android app with button to detect devices, and connect the cc2650stk. Can you please help me with this?

**Comment by lemariva** [comment]
You can find more info about the application here:
* https://lemariva.com/blog/2017/07/sensortag-cc2650
* https://lemariva.com/blog/2018/06/ti-sensor-tag-working-on-android-8-1

The application is an old and open source version of the following: https://play.google.com/store/apps/details?id=com.ti.ble.sensortag
You can use the application as basis for your developments.
