### ISSUE TITLE
The app crashes when I push to non-default(non-IBM) cloud

### ISSUE THREAD

**Issue by xyziven** [lemariva/SensorTag-CC2650#2]
I created a custom connection to my mqtt broker, the app keeps crash once I press the button "push to cloud". It works if I push to the default one(ibm IoT)

**Comment by lemariva** [comment]
Hi, it seems that it is not a problem of the application, it's a problem of the custom connection. You need to debug your own application to find the problem. I don't even have your code.

**Comment by xyziven** [comment]
Thank you @lemariva ! I got it work on another android device.
